version: '3.8'

services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - poli-network

networks:
  poli-network:
    driver: bridge
    name: poli-network